version: '3.1'

services:
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/app/logs:/usr/src/app/logs
    environment:
      MYSQL_DATABASE: carry
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3308:3306"
