database:
  image: mysql/mysql-server:8.0
  container_name: mysql-server
  command: --default-authentication-plugin=mysql_native_password
  volumes:
    - ./volumes/mysql:/var/lib/mysql
    - ./init_scripts:/docker-entrypoint-initdb.d
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "carry"
    MYSQL_USER: "carry"
    MYSQL_PASSWORD: "test123"
    MYSQL_ROOT_PASSWORD: "test123"