
CREATE DATABASE IF NOT EXISTS carry;

USE carry;

CREATE TABLE IF NOT EXISTS orders (id INT(100) NOT NULL AUTO_INCREMENT, dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, name VARCHAR(255), lastname VARCHAR(255), phone VARCHAR(255), delivery_address VARCHAR(255), city VARCHAR(255), zip VARCHAR(255), details VARCHAR(255), PRIMARY KEY(id));
